//定义一个地址参数列表,这个也是每做一个网站的，就添加一个新的对象

//key:识别的关键字
//jsFileName:js文件名，用于创建js文件和对象（如果已经创建就不会动这个文件了，请放心跑自动编码）
//url:匹配的url，用于清单匹配（非常重要，具体写法请看清单的匹配规则）
//originUrl:根路径，用来看这个网站是否被我们支持，但具体能下载还要去阅读页（记得去掉末尾的斜杠）
//regex:匹配的正则（很重要，用这个来匹配地址栏的链接，要阅读页的正则表达式）
//cookiesUrl:（非必填）如果网站需要获取cookie，在这里写一级域名

//以下字段用于ui展示的(修改这些不需要运行自动编码了，修改上面的内容，记得重新运行自动编码)

//name:网站的名字
//supportMsg:支持但不在阅读页的提示
//loadingMsg:正在加载漫画信息的提示
//downloadMsg:加载数据完毕的其他提示
//loadStopMsg：下载中断的提示


var webList = [{
  key: 'bili',
  jsFileName: 'biliComic',
  url: 'https://manga.bilibili.com/mc*',
  originUrl: 'manga.bilibili.com',
  regex: /^https:\/\/manga\.bilibili\.com\/mc(\d+)\/(\d+).*/,
  name: "bilibili漫画",
  supportMsg: ["b漫下载需要保证用户<b>购买了</b>该话内容，如没有购买，只能下载第一页", "可以右键另存为页面图片（b的页面图片并非原图，推荐下载）"],
  loadingMsg: [],
  downloadMsg: ["b漫下载需要保证用户<b>购买了</b>该话内容，如没有购买，只能下载第一页", "可以右键另存为页面图片（b的页面图片并非原图，推荐下载）", "目前仅支持单独话下载，不支持整本下载"],
  loadStopMsg: "",
},
{
  key: 'pixiv',
  jsFileName: 'pixivComic',
  url: 'https://comic.pixiv.net/viewer/stories/*',
  originUrl: 'comic.pixiv.net',
  regex: /^https:\/\/comic\.pixiv\.net\/viewer\/stories\/.*/,
  name: "pixivコミック",
  supportMsg: ["pixiv被墙，可能下载速度偏慢"],
  loadingMsg: [],
  downloadMsg: ["pixiv被墙，可能下载速度偏慢", "如下载中途失败，请删除已经下载的图片再重新下载"],
  loadStopMsg: "",
},
{
  key: 'qq',
  jsFileName: 'acQQ',
  url: 'https://ac.qq.com/ComicView/index/id/*',
  originUrl: 'ac.qq.com',
  regex: /^https:\/\/ac\.qq\.com\/ComicView\/index\/id\/(\d+)\/cid\/(\d+).*/,
  name: "腾讯动漫",
  supportMsg: [],
  loadingMsg: [],
  downloadMsg: ["可以右键另存为单张图片"],
  loadStopMsg: "",
},
{
  key: 'cmoa',
  jsFileName: 'cmoaComic',
  url: 'https://www.cmoa.jp/bib/*',
  originUrl: 'cmoa.jp',
  regex: /^https:\/\/www\.cmoa\.jp\/bib\.*/,
  name: "コミックシーモア",
  supportMsg: ["页面加载完毕后再启动插件"],
  loadingMsg: [],
  downloadMsg: [],
  loadStopMsg: "",
},
{
  key: 'corona',
  jsFileName: 'coronaComic',
  url: 'https://to-corona-ex.com/episodes/*',
  originUrl: 'to-corona-ex.com',
  regex: /^https:\/\/to-corona-ex\.com\/episodes\/\.*/,
  name: "コロナEX｜TOブックスの公式Web漫画サイト",
  supportMsg: [],
  loadingMsg: [],
  downloadMsg: ["可以右键保存单页，但图片非原图，不建议"],
  loadStopMsg: "",
},
{
  key: 'zerosum',
  jsFileName: 'zerosumComic',
  url: 'https://zerosumonline.com/episode/*',
  originUrl: 'zerosumonline.com',
  regex: /^https:\/\/zerosumonline\.com\/episode\/\.*/,
  name: "ゼロサムオンライン",
  supportMsg: ["zerosum被墙，可能下载速度偏慢", "可以右键保存单张图片"],
  loadingMsg: [],
  downloadMsg: ["zerosum被墙，可能下载速度偏慢", "如下载中途失败，请删除已经下载的图片再重新下载", "可以右键保存单张图片"],
  loadStopMsg: "",
},
{
  key: 'ganma',
  jsFileName: 'ganmaComic',
  url: 'https://ganma.jp/*',
  originUrl: 'ganma.jp',
  regex: /^https:\/\/ganma\.jp\/.*/,
  name: "GANMA!(ガンマ)",
  supportMsg: ["可能当前页不是阅读页面，无法下载", "请点击到阅读漫画页下载"],
  loadingMsg: ["可能当前页不是阅读页面，无法下载", "请点击到阅读漫画页下载"],
  downloadMsg: [],
  loadStopMsg: "",
},
{
  key: 'pocket',
  jsFileName: 'pocketComic',
  url: 'https://pocket.shonenmagazine.com/episode/*',
  originUrl: 'shonenmagazine.com',
  regex: /^https:\/\/pocket\.shonenmagazine\.com\/episode\/.*/,
  name: "マガポケ",
  supportMsg: [],
  loadingMsg: ["支持右键保存单图"],
  downloadMsg: ["支持右键保存单图"],
  loadStopMsg: "",
},
{
  key: 'hakusensha',
  jsFileName: 'hakusenshaComic',
  url: 'https://bsreader.hakusensha-e.net/?param=*',
  originUrl: 'hakusensha-e.net',
  regex: /^https:\/\/bsreader\.hakusensha-e\.net\/\?param=.*/,
  name: "白泉社e-net!",
  supportMsg: [],
  loadingMsg: ["试阅只能下载十页左右，请购买后再试", "白泉社无法获取漫画信息，只能展示书籍内容目录", "杂志类页数较多，可能下载中途出错，请删除已下载的图片重新下载",],
  downloadMsg: ["试阅只能下载十页左右，请购买后再试", "白泉社无法获取漫画信息，只能展示书籍内容目录",],
  loadStopMsg: "",
},
{
  key: 'jump',
  jsFileName: 'jumpComic',
  url: 'https://shonenjumpplus.com/episode/*',
  originUrl: 'shonenjumpplus.com',
  regex: /^https:\/\/shonenjumpplus\.com\/episode.*/,
  name: "少年ジャンプ＋",

  supportMsg: [],
  loadingMsg: ["支持右键保存单张图片", "请右键偏中位置才能选中图片"],
  downloadMsg: ["支持右键保存单张图片", "请右键偏中位置才能选中图片，左边的图片右键右半部分，右边的在左半部分"],
  loadStopMsg: "",
},
{
  key: 'bw',
  jsFileName: 'bwBook',
  url: 'https://viewer.bookwalker.jp/*/*/viewer.html*',
  originUrl: 'bookwalker.jp',
  regex: /^https:\/\/viewer\.bookwalker\.jp\.*/,
  name: "BOOK WALKER",

  supportMsg: [],
  loadingMsg: ["点击下载后，请<b>手动翻阅</b>", "翻阅过程中会自动下载", "如有下载遗漏页，可以回翻会自动补充下载"],
  downloadMsg: ["请<b>手动翻阅</b>", "翻阅过程中会自动下载", "如有下载遗漏页，可以回翻会自动补充下载"],
  loadStopMsg: "",
},
{
  key: 'bwTrial',
  jsFileName: 'bwBookTrial',
  url: 'https://viewer-trial.bookwalker.jp/*/*/viewer.html*',
  originUrl: 'bookwalker.jp',
  regex: /^https:\/\/viewer-trial\.bookwalker\.jp\.*/,
  name: "BOOK WALKER (试阅)",

  supportMsg: [],
  loadingMsg: ["如需下载整本，请前往购买", "试阅内容约可下载10页左右"],
  downloadMsg: ["如需下载整本，请前往购买", "试阅内容约可下载10页左右"],
  loadStopMsg: "",
},
{
  key: 'bw',
  jsFileName: 'bwBook',
  url: 'https://pcreader.bookwalker.com.tw/*/*/viewer.html*',
  originUrl: 'bookwalker.com.tw',
  regex: /^https:\/\/pcreader\.bookwalker\.com\.tw\.*/,
  name: "BOOK☆WALKER 台灣漫讀",

  supportMsg: [],
  loadingMsg: ["点击下载后，请<b>手动翻阅</b>", "翻阅过程中会自动下载", "如有下载遗漏页，可以回翻会自动补充下载", "开始页下载的第一页容易被遗漏，请回翻"],
  downloadMsg: ["请<b>手动翻阅</b>", "翻阅过程中会自动下载", "如有下载遗漏页，可以回翻会自动补充下载", "开始页下载的第一页容易被遗漏，请回翻"],
  loadStopMsg: "",
},
{
  key: 'bwTrial',
  jsFileName: 'bwBookTrial',
  url: 'https://preview.bookwalker.com.tw/*/*/viewer.html*',
  originUrl: 'bookwalker.com.tw',
  regex: /^https:\/\/preview\.bookwalker\.com\.tw\.*/,
  name: "BOOK☆WALKER 台灣漫讀 (试阅)",

  supportMsg: [],
  loadingMsg: ["如需下载整本，请前往购买", "试阅内容约可下载10页左右"],
  downloadMsg: ["如需下载整本，请前往购买", "试阅内容约可下载10页左右"],
  loadStopMsg: "",
},
{
  key: 'dmmFree',
  jsFileName: 'dmmBook',
  url: 'https://book.dmm.com/free_streaming/*/*',
  originUrl: 'dmm.com',
  regex: /^https:\/\/book\.dmm\.com\/free_streaming\.*/,
  name: "DMMブックス",
  cookiesUrl: "dmm.com",
  supportMsg: [],
  loadingMsg: ["点击下载将会下载整本", "支持右键保存单张图片"],
  downloadMsg: ["支持右键保存单张图片"],
  loadStopMsg: "",
},
{
  key: 'renta',
  jsFileName: 'rentaBook',
  url: 'https://dre-viewer.papy.co.jp/sc/view_*',
  originUrl: 'papy.co.jp',
  regex: /^https:\/\/dre-viewer\.papy\.co\.jp\/sc\/view_.*/,
  name: "Renta!",

  supportMsg: ["<b style='color:red'>**</b>如果阅读时浏览器打开新页面<b>无法使用插件</b>，请<b>复制链接</b>到新标签打开即可"],
  loadingMsg: ["支持右键保存单张图片"],
  downloadMsg: ["支持右键保存单张图片"],
  loadStopMsg: "",
},
{
  key: 'fuz',
  jsFileName: 'fuzComic',
  url: 'https://comic-fuz.com/*/*',
  originUrl: 'comic-fuz.com',
  regex: /^https:\/\/comic-fuz\.com\/(book\/viewer|manga)\/.*/,
  name: "COMIC FUZ(芳文社公式)",
  supportMsg: ["该网站下载需要<b>手动翻页</b>"],
  loadingMsg: ["请<b>手动翻页</b>", "翻页会自动下载", "支持右键另存为下载（另存为时需要手动改一下后缀名png或者jpg）"],
  downloadMsg: ["请<b>手动翻页</b>", "翻页会自动下载", "支持右键另存为下载（另存为时需要手动改一下后缀名png或者jpg）"],
  loadStopMsg: "",
},
{
  key: 'valkyrie',
  jsFileName: 'valkyrieComic',
  url: 'https://www.comic-valkyrie.com/samplebook/*',
  originUrl: 'comic-valkyrie.com',
  regex: /^https:\/\/www\.comic-valkyrie\.com\/samplebook\/.*/,
  name: "コミックヴァルキリー公式サイト",
  supportMsg: [],
  loadingMsg: ["该网站不翻墙访问下载速度较慢，请耐心等待"],
  downloadMsg: ["该网站不翻墙访问下载速度较慢，请耐心等待"],
  loadStopMsg: "",
},

{
  key: 'nico',
  jsFileName: 'nicoComic',
  url: 'https://seiga.nicovideo.jp/watch/*',
  originUrl: 'nicovideo.jp',
  regex: /^https:\/\/seiga\.nicovideo\.jp\/watch\/.*/,
  name: "ニコニコ漫画 ",
  supportMsg: [],
  loadingMsg: [],
  downloadMsg: [],
  loadStopMsg: "",
},
{
  key: 'kuaikan',
  jsFileName: 'kuaikanComic',
  url: 'https://www.kuaikanmanhua.com/webs/comic-next/*',
  originUrl: 'kuaikanmanhua.com',
  regex: /^https:\/\/www\.kuaikanmanhua\.com\/webs\/comic-next\/.*/,
  name: "快看漫画 ",
  supportMsg: [],
  loadingMsg: [],
  downloadMsg: [],
  loadStopMsg: "",
},
{
  key: 'honto',
  jsFileName: 'hontoBook',
  url: 'https://mbj-bs.pf.mobilebook.jp/*/*/index.php?*',
  originUrl: 'honto.jp',
  regex: /^https:\/\/mbj-bs\.pf\.mobilebook\.jp\/.*/,
  name: "総合書店honto",
  supportMsg: [],
  loadingMsg: [],
  downloadMsg: [],
  loadStopMsg: "",
},
{
  key: 'dlLsite',
  jsFileName: 'dlLsiteBook',
  url: 'https://play.dlsite.com/csr/viewer/*',
  originUrl: 'dlsite.com',
  regex: /^https:\/\/play\.dlsite\.com\/csr\/viewer\/.*/,
  name: "DLsite コミック",
  supportMsg: [],
  loadingMsg: [],
  downloadMsg: [],
  loadStopMsg: "",
},
{
  key: 'gangan',
  jsFileName: 'ganganComic',
  url: 'https://www.ganganonline.com/title/*/chapter/*',
  originUrl: 'ganganonline.com',
  regex: /^https:\/\/www\.ganganonline\.com\/title\/.*/,
  name: "ガンガンONLINE",
  supportMsg: [],
  loadingMsg: [],
  downloadMsg: [],
  loadStopMsg: "",
},
{
  key: 'bunch',
  jsFileName: 'bunchComic',
  url: 'https://kuragebunch.com/episode/*',
  originUrl: 'kuragebunch.com',
  regex: /^https:\/\/kuragebunch\.com\/episode\/.*/,
  name: "くらげバンチ",
  supportMsg: [],
  loadingMsg: [],
  downloadMsg: [],
  loadStopMsg: "",
},
{
  key: 'border',
  jsFileName: 'borderComic',
  url: 'https://comicborder.com/episode/*',
  originUrl: 'comicborder.com',
  regex: /^https:\/\/comicborder\.com\/episode\/.*/,
  name: "コミックボーダー",
  supportMsg: [],
  loadingMsg: [],
  downloadMsg: [],
  loadStopMsg: "",
},

{
  key: 'urasunday',
  jsFileName: 'urasundayComic',
  url: 'https://urasunday.com/title/*/*',
  originUrl: 'urasunday.com',
  regex: /^https:\/\/urasunday\.com\/title\/.*/,
  name: "裏サンデー",
  supportMsg: [],
  loadingMsg: [],
  downloadMsg: [],
  loadStopMsg: "",
},

{
  key: 'booklive',
  jsFileName: 'bookliveBook',
  url: 'https://booklive.jp/bviewer/*',
  originUrl: 'booklive.jp',
  regex: /^https:\/\/booklive\.jp\/bviewer\/.*/,
  name: "booklive",
  supportMsg: [],
  loadingMsg: [],
  downloadMsg: [],
  loadStopMsg: "",
},
{
  key: 'championcross',
  jsFileName: 'championcross',
  url: 'https://championcross.jp/episodes/*',
  originUrl: 'championcross.jp',
  regex: /^https:\/\/championcross\.jp\/episodes\/.*/,
  name: "秋田書店",
  supportMsg: [],
  loadingMsg: [],
  downloadMsg: [],
  loadStopMsg: "",
},
{
  key: 'ichijin',
  jsFileName: 'ichijin',
  url: 'https://ichijin-plus.com/episodes/*',
  originUrl: 'ichijin-plus.com',
  regex: /^https:\/\/ichijin-plus\.com\/episodes\/.*/,
  name: "一迅プラス",
  supportMsg: [],
  loadingMsg: [],
  downloadMsg: [],
  loadStopMsg: "",
},

{
  key: 'earthstar',
  jsFileName: 'earthstar',
  url: 'https://comic-earthstar.com/episode/*',
  originUrl: 'comic-earthstar.com',
  regex: /^https:\/\/comic-earthstar\.com\/episode\/.*/,
  name: "コミック アース・スター",
  supportMsg: [],
  loadingMsg: [],
  downloadMsg: [],
  loadStopMsg: "",
},

{
  key: 'heros',
  jsFileName: 'heros',
  url: 'https://viewer.heros-web.com/episode/*',
  originUrl: 'heros-web.com',
  regex: /^https:\/\/viewer\.heros-web\.com\/episode\/.*/,
  name: "コミプレ｜ヒーローズ",
  supportMsg: [],
  loadingMsg: [],
  downloadMsg: [],
  loadStopMsg: "",
},
{
  key: 'voltage',
  jsFileName: 'voltage',
  url: 'https://voltage-comics.com/viewer/*',
  originUrl: 'voltage-comics.com',
  regex: /^https:\/\/voltage-comics\.com\/viewer\/.*/,
  name: "ぼるコミ",
  supportMsg: [],
  loadingMsg: [],
  downloadMsg: [],
  loadStopMsg: "",
}, {
  key: 'growl',
  jsFileName: 'growl',
  url: 'https://comic-growl.com/episode/*',
  originUrl: 'comic-growl.com',
  regex: /^https:\/\/comic-growl\.com\/episode\/.*/,
  name: "コミックグロウル",
  supportMsg: [],
  loadingMsg: [],
  downloadMsg: [],
  loadStopMsg: "",
}, {
  key: 'trail',
  jsFileName: 'trail',
  url: 'https://comic-trail.com/episode/*',
  originUrl: 'comic-trail.com',
  regex: /^https:\/\/comic-trail\.com\/episode\/.*/,
  name: "コミックトレイル",
  supportMsg: [],
  loadingMsg: [],
  downloadMsg: [],
  loadStopMsg: "",
}, {
  key: 'polaris',
  jsFileName: 'polaris',
  url: 'https://comic-polaris.jp/ptdata/*',
  originUrl: 'comic-polaris.jp',
  regex: /^https:\/\/comic-polaris\.jp\/ptdata\/.*/,
  name: "COMICポラリス",
  supportMsg: [],
  loadingMsg: [],
  downloadMsg: [],
  loadStopMsg: "",
}, {
  key: 'meteor',
  jsFileName: 'meteor',
  url: 'https://comic-meteor.jp/ptdata/*',
  originUrl: 'comic-meteor.jp',
  regex: /^https:\/\/comic-meteor\.jp\/ptdata\/.*/,
  name: "COMICメテオ",
  supportMsg: [],
  loadingMsg: [],
  downloadMsg: [],
  loadStopMsg: "",
}, {
  key: 'zenon',
  jsFileName: 'zenon',
  url: 'https://comic-zenon.com/episode/*',
  originUrl: 'comic-zenon.com',
  regex: /^https:\/\/comic-zenon\.com\/episode\/.*/,
  name: "ゼノン編集部",
  supportMsg: [],
  loadingMsg: [],
  downloadMsg: [],
  loadStopMsg: "",
}, {
  key: 'action',
  jsFileName: 'action',
  url: 'https://comic-action.com/episode/*',
  originUrl: 'comic-action.com',
  regex: /^https:\/\/comic-action\.com\/episode\/.*/,
  name: "webアクション",
  supportMsg: [],
  loadingMsg: [],
  downloadMsg: [],
  loadStopMsg: "",
},
]